### ISSUE TITLE
GVLError caused by incompatibility with latest GVL or invalid file

### ISSUE THREAD

**Issue by andreas-hartmann** [InteractiveAdvertisingBureau/iabtcf-es#393]
We are experiencing:
```GVLError.js:1 Uncaught (in promise) GVLError: Cannot read properties of undefined (reading 'consent')
    at new t (GVLError.js:1:647)
    at t.<anonymous> (GVL.js:1:4117)
    at GVL.js:1:1826
    at Object.next (GVL.js:1:1142)
    at s (GVL.js:1:635)```
When loading the latest version of https://vendor-list.consensu.org/v2/vendor-list.json as published yesterday. 
The issue appears to be caused by https://github.com/InteractiveAdvertisingBureau/iabtcf-es/blob/master/modules/core/src/GVL.ts#L602 where the purposes of each vendor are mapped to a lookup table of defined purposes. Unfortunately one of the vendors defines purpose 11 in this newest version of the GVL which is is not defined in that same file (only 1-10 are). This causes this error. The relevant vendor is:
```        "164": {
            "id": 164,
            "name": "Outbrain UK Ltd",
            "purposes": [
                1,
                2,
                3,
                4,
                5,
                6,
                7,
                8,
                9,
                10,
                11
            ]```

This is quite clearly an error in the GVL, but either way this library should not catastrophically fail in such a case. IMO there should be a softer behavior, such as a warning, a skipped vendor or some such solution.

**Comment by dmdabbs** [comment]
>Same, the issue was appeared after using the new version 197, but 196 works well

The issue persists even with the new GVL revision with the mistakenly added Purpose 11 removed?

cc: @HeinzBaumann

**Comment by andreas-hartmann** [comment]
We also rolled back to 196, didn't try removing the purpose though.

**Comment by HeinzBaumann** [comment]
There is new updated GVL posted today. It should be all fixed.

**Comment by andreas-hartmann** [comment]
As a note, the new GVL has the same version 197 as the broken one but a new timestamp. It also contains other changes, so it's not clear to me why they didn't give it a new version number. Be aware of this in case your implementation is checking for the version.

**Comment by adriafolchmrf** [comment]
Following up on this, even though version 197 is correct in https://vendor-list.consensu.org/v2/vendor-list.json, when requesting it through https://vendor-list.consensu.org/v2/archives/vendor-list-v197.json the error still persist. Are there any plans to update this one as well?
